// Generated by https://quicktype.io

export interface CoinPrice {
    TYPE:            string;
    MARKET:          string;
    FROMSYMBOL:      string;
    TOSYMBOL:        string;
    FLAGS:           string;
    PRICE:           number;
    LASTUPDATE:      number;
    LASTVOLUME:      number;
    LASTVOLUMETO:    number;
    LASTTRADEID:     number;
    VOLUME24HOUR:    number;
    VOLUME24HOURTO:  number;
    OPEN24HOUR:      number;
    HIGH24HOUR:      number;
    LOW24HOUR:       number;
    LASTMARKET:      string;
    CHANGE24HOUR:    number;
    CHANGEPCT24HOUR: number;
    Eur: string;
    USD: string;
}


