// Generated by https://quicktype.io

export interface CoinInfo {
    Id:        string;
    Url:       string;
    ImageUrl:  string;
    Name:      string;
    CoinName:  string;
    FullName:  string;
    Algorithm: string;
    ProofType: string;
    TotalCoinSupply?: number;
    Symbol:    string;
    SortOrder: string;
    EUR?: number;
    USD?: number;
}


